# Generated by Django 5.1.6 on 2025-03-12 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0003_alter_mehrum_slika'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mehrum',
            name='datum',
        ),
        migrations.AddField(
            model_name='mehrum',
            name='datum_dzenaze',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mehrum',
            name='datum_rodjenja',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
