# Generated by Django 5.1.6 on 2025-03-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0004_remove_mehrum_datum_mehrum_datum_dzenaze_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mehrum',
            name='text',
            field=models.TextField(default='template'),
            preserve_default=False,
        ),
    ]
