# Generated by Django 5.1.6 on 2025-03-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0005_mehrum_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mehrum',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d'),
        ),
    ]
